name: build-page
on:
  push:
    branches: [ main ]
jobs: 
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install and build
      - run: npm install && npm run build

      - name: depoly
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public


